mode:
  develop: true
db:
  dsn: root:asd123@tcp(127.0.0.1:3306)/gogofly?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConn: 10  # 最多空闲连接数
  maxOpenConn: 10  # 最多打开连接数

server:
  port: 8888

jwt:
  xx: 30
  tokenExpire: 30 # token有效时长，分钟  用GetDuration()获取
  signingKey: gogofly.cn # 签名使用的key
log:
  MaxSize: 10 # 日志文件最大尺寸（M）超出后自动分割
  MaxBackups: 10 #保留旧文件的最大个数
  MaxAge: 28 #天